[package]
name = "lichen_tui"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono-tz.workspace = true
color-eyre.workspace = true
crossterm.workspace = true
tokio.workspace = true
ratatui.workspace = true
system = { path = "../crates/system" }
tui = { path = "../crates/tui" }
