[workspace]
members = [
    "crates/*",
    "lichen_tui",
    "lichen_cli",
]
resolver = "2"

[workspace.dependencies]
bitflags = "2.5.0"
chrono = { version = "0.4.38", features = ["unstable-locales"] }
chrono-tz = "0.9.0"
color-eyre = { version = "0.6.3", features = ["issue-url"] }
crossterm = { version = "0.27.0", features = ["serde", "event-stream"] }
futures = "0.3.30"
libc = "0.2.155"
log = "0.4.21"
ratatui = { version = "0.26.3", features = ["all-widgets", "macros", "document-features", "crossterm", "serde", "unstable"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["full"] }
tokio-util = "0.7.11"
