[workspace]
members = [
    "crates/*",
    "lichen_tui",
    "lichen_cli",
]
resolver = "2"

[workspace.dependencies]
bitflags = "2.6.0"
chrono = { version = "0.4.38", features = ["unstable-locales"] }
chrono-tz = "0.9.0"
color-eyre = { version = "0.6.3", features = ["issue-url"] }
crossterm = { version = "0.27.0", features = ["serde", "event-stream"] }
human_bytes = "0.4.3"
futures = "0.3.30"
libc = "0.2.155"
log = "0.4.21"
ratatui = { version = "0.27.0", features = ["all-widgets", "macros", "document-features", "crossterm", "serde", "unstable"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.118"
superblock = { git = "https://github.com/serpent-os/blsforme.git", rev = "abc2fcc025975ebff714835849c94159f81990d5"}
topology = { git = "https://github.com/serpent-os/blsforme.git", rev = "abc2fcc025975ebff714835849c94159f81990d5"}
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["full"] }
tokio-util = "0.7.11"
tokio-stream = { version = "0.1.15", features = ["full"] }
